# Puerto del servidor
server.port=9090
spring.application.name=MagicShop

# JPA
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bdmagicshop
spring.datasource.username=root
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=sAW0dGkh+OWhl9+U3f1GyV9LSGdAf0g+RJHJMswI3kQ=
